# RUCKUS DSO Dashboard - installer (Windows PowerShell).
# Idempotent. Creates venv, installs deps, writes RUCKUS\.env, then launches
# the dashboard in the foreground for first verification.
#
# Non-interactive mode: set $env:RUCKUS_INSTALL_NONINTERACTIVE = "1" and supply
# RUCKUS_INSTALL_HOST / RUCKUS_INSTALL_PORT / RUCKUS_INSTALL_ALLOWED /
# RUCKUS_INSTALL_NEWUI / RUCKUS_INSTALL_BROWSER as needed.
$ErrorActionPreference = "Stop"
$RepoRoot = Split-Path -Parent $PSScriptRoot
Set-Location $RepoRoot

$EnvFile = "RUCKUS\.env"

# --- 1. Python check ---
$py = Get-Command python -ErrorAction SilentlyContinue
if (-not $py) {
    Write-Error "python not found. Install Python 3.10+ first."
    exit 1
}
$ver = & python -c "import sys; print(f'{sys.version_info.major}.{sys.version_info.minor}')"
if ($ver -notin @("3.10", "3.11", "3.12", "3.13")) {
    Write-Error "Python $ver found, need 3.10+."
    exit 1
}
Write-Host "OK Python $ver"

# --- 2. venv ---
if (-not (Test-Path ".venv")) {
    & python -m venv .venv
    Write-Host "OK created .venv"
}
& .venv\Scripts\python.exe -m pip install --quiet --upgrade pip
& .venv\Scripts\python.exe -m pip install --quiet -e RUCKUS
Write-Host "OK installed dependencies"

# --- 3. .env (only if missing) ---
if (-not (Test-Path $EnvFile)) {
    if ($env:RUCKUS_INSTALL_NONINTERACTIVE -eq "1") {
        $hostBind = if ($env:RUCKUS_INSTALL_HOST) { $env:RUCKUS_INSTALL_HOST } else { "127.0.0.1" }
        $port = if ($env:RUCKUS_INSTALL_PORT) { $env:RUCKUS_INSTALL_PORT } else { "8444" }
        $allowed = if ($env:RUCKUS_INSTALL_ALLOWED) { $env:RUCKUS_INSTALL_ALLOWED } else { "" }
        $newui = if ($env:RUCKUS_INSTALL_NEWUI) { $env:RUCKUS_INSTALL_NEWUI } else { "y" }
        $browser = if ($env:RUCKUS_INSTALL_BROWSER) { $env:RUCKUS_INSTALL_BROWSER } else { "n" }
    } else {
        Write-Host ""
        Write-Host "Initial configuration (press Enter for defaults):"
        $hostBind = Read-Host "  Bind host [127.0.0.1]"
        if (-not $hostBind) { $hostBind = "127.0.0.1" }
        $port = Read-Host "  HTTPS port [8444]"
        if (-not $port) { $port = "8444" }
        if ($hostBind -ne "127.0.0.1" -and $hostBind -ne "localhost") {
            $allowed = Read-Host "  Allowed SmartZone hosts (CSV, required for non-loopback)"
            if (-not $allowed) {
                Write-Error "allowed-hosts required for non-loopback bind."
                exit 1
            }
        } else {
            $allowed = ""
        }
        $newui = Read-Host "  Enable new UI? [Y/n]"
        if (-not $newui) { $newui = "y" }
        $browser = Read-Host "  Auto-open browser on launch? [Y/n]"
        if (-not $browser) { $browser = "y" }
    }

    $secret = & python -c "import secrets; print(secrets.token_urlsafe(48))"
    $newuiVal = if ($newui.ToLower().StartsWith("n")) { "0" } else { "1" }
    $browserVal = if ($browser.ToLower().StartsWith("n")) { "0" } else { "1" }
    $stamp = (Get-Date).ToUniversalTime().ToString("yyyy-MM-ddTHH:mm:ssZ")

    $content = @"
# Generated by install.ps1 on $stamp
RUCKUS_DASHBOARD_HOST=$hostBind
RUCKUS_DASHBOARD_PORT=$port
RUCKUS_ALLOWED_HOSTS=$allowed
RUCKUS_ENABLE_NEW_UI=$newuiVal
RUCKUS_OPEN_BROWSER=$browserVal
RUCKUS_VERIFY_TLS=true
RUCKUS_SHOW_DEBUG=0
FLASK_SECRET_KEY=$secret
"@
    Set-Content -Path $EnvFile -Value $content -Encoding utf8 -NoNewline
    # Restrict ACL to current user
    icacls $EnvFile /inheritance:r /grant:r "$($env:USERNAME):F" | Out-Null
    Write-Host "OK wrote $EnvFile (ACL restricted to $($env:USERNAME))"
} else {
    Write-Host "OK $EnvFile already exists, keeping"
}

# --- 4. first-run verify (skip in non-interactive mode) ---
if ($env:RUCKUS_INSTALL_NONINTERACTIVE -eq "1") {
    Write-Host "OK install complete (non-interactive). Run .\scripts\start.ps1 to launch."
    exit 0
}

Write-Host ""
Write-Host "Launching dashboard in foreground for verify."
Write-Host "Hit Ctrl+C when satisfied, then run: .\scripts\start.ps1"
Write-Host ""

# Load .env into process env
Get-Content $EnvFile | ForEach-Object {
    if ($_ -match '^([^#=]+)=(.*)$') {
        [Environment]::SetEnvironmentVariable($matches[1].Trim(), $matches[2].Trim(), "Process")
    }
}
& .venv\Scripts\python.exe -m ruckus_dashboard
