#!/usr/bin/env bash
# RUCKUS DSO Dashboard — installer (Linux / macOS).
# Idempotent: safe to re-run. Creates venv, installs deps, writes RUCKUS/.env,
# then launches the dashboard in the foreground for first verification.
#
# Non-interactive mode (CI / automation): set RUCKUS_INSTALL_NONINTERACTIVE=1
# and supply RUCKUS_INSTALL_HOST / RUCKUS_INSTALL_PORT / RUCKUS_INSTALL_ALLOWED /
# RUCKUS_INSTALL_NEWUI / RUCKUS_INSTALL_BROWSER as needed.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$REPO_ROOT"

ENV_FILE="RUCKUS/.env"
PY="${PYTHON:-python3}"

# ─── 1. Python check ─────────────────────────────────────────────────────────
if ! command -v "$PY" >/dev/null 2>&1; then
  echo "ERROR: $PY not found. Install Python 3.10+ first." >&2
  exit 1
fi
PYVER="$("$PY" -c 'import sys; print(f"{sys.version_info.major}.{sys.version_info.minor}")')"
case "$PYVER" in
  3.10|3.11|3.12|3.13) ;;
  *) echo "ERROR: Python $PYVER found, need 3.10+." >&2; exit 1 ;;
esac
echo "✓ Python $PYVER"

# ─── 2. venv ─────────────────────────────────────────────────────────────────
if [ ! -d ".venv" ]; then
  "$PY" -m venv .venv
  echo "✓ created .venv"
fi
# shellcheck disable=SC1091
source .venv/bin/activate
pip install --quiet --upgrade pip
pip install --quiet -e RUCKUS
echo "✓ installed dependencies"

# ─── 3. .env (only if missing) ────────────────────────────────────────────────
if [ ! -f "$ENV_FILE" ]; then
  if [ "${RUCKUS_INSTALL_NONINTERACTIVE:-0}" = "1" ]; then
    HOST="${RUCKUS_INSTALL_HOST:-127.0.0.1}"
    PORT="${RUCKUS_INSTALL_PORT:-8444}"
    ALLOWED="${RUCKUS_INSTALL_ALLOWED:-}"
    NEWUI="${RUCKUS_INSTALL_NEWUI:-y}"
    BROWSER="${RUCKUS_INSTALL_BROWSER:-n}"
  else
    echo
    echo "Initial configuration (press Enter for defaults):"
    read -rp "  Bind host [127.0.0.1]: " HOST; HOST="${HOST:-127.0.0.1}"
    read -rp "  HTTPS port [8444]: " PORT; PORT="${PORT:-8444}"
    if [ "$HOST" != "127.0.0.1" ] && [ "$HOST" != "localhost" ]; then
      read -rp "  Allowed SmartZone hosts (CSV, required for non-loopback): " ALLOWED
      if [ -z "$ALLOWED" ]; then
        echo "ERROR: allowed-hosts required for non-loopback bind." >&2
        exit 1
      fi
    else
      ALLOWED=""
    fi
    read -rp "  Enable new UI? [Y/n]: " NEWUI; NEWUI="${NEWUI:-y}"
    read -rp "  Auto-open browser on launch? [Y/n]: " BROWSER; BROWSER="${BROWSER:-y}"
  fi

  SECRET="$("$PY" -c 'import secrets; print(secrets.token_urlsafe(48))')"

  cat > "$ENV_FILE" <<EOF
# Generated by install.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
RUCKUS_DASHBOARD_HOST=$HOST
RUCKUS_DASHBOARD_PORT=$PORT
RUCKUS_ALLOWED_HOSTS=$ALLOWED
RUCKUS_ENABLE_NEW_UI=$([ "$(printf '%s' "$NEWUI" | cut -c1)" = "n" ] && echo 0 || echo 1)
RUCKUS_OPEN_BROWSER=$([ "$(printf '%s' "$BROWSER" | cut -c1)" = "n" ] && echo 0 || echo 1)
RUCKUS_VERIFY_TLS=true
RUCKUS_SHOW_DEBUG=0
FLASK_SECRET_KEY=$SECRET
EOF
  chmod 600 "$ENV_FILE"
  echo "✓ wrote $ENV_FILE (chmod 600)"
else
  echo "✓ $ENV_FILE already exists, keeping"
fi

# ─── 4. first-run verify (skip in non-interactive mode) ───────────────────────
if [ "${RUCKUS_INSTALL_NONINTERACTIVE:-0}" = "1" ]; then
  echo "✓ install complete (non-interactive). Run ./scripts/start.sh to launch."
  exit 0
fi

echo
echo "Launching dashboard in foreground for verify."
echo "Hit Ctrl+C when satisfied, then run: ./scripts/start.sh"
echo

set -a; source "$ENV_FILE"; set +a
exec "$PY" -m ruckus_dashboard
